### ISSUE TITLE
Implement the tracker Si sensor charge deposition simulation.

### ISSUE THREAD

**Issue by omar-moreno** [LDMX-Software/ldmx-sw#334]

**Comment by omar-moreno** [comment]
Charge deposition simulation is based on one used for CDF (See attached pdf)
[Uploading cdf5080_TOYSiChargeDepPadova.pdf…]()

**Comment by ASPatterson** [comment]
Hey Omar, the pdf link is broken and I can't get at note 5080 without logging into CDF. Given that it's ... historical, could you post it here?
https://www-cdf.fnal.gov/cdfnotes/cdf5080_TOYSiChargeDepPadova.ps.gz
