### ISSUE TITLE
put sorted sim hit collections into workflow

### ISSUE THREAD

**Issue by awhitbeck** [LDMX-Software/ldmx-sw#412]
- Added simHit sorting processors to v3 workflow
- Add capability to override default sim hit collections used to for ecal and hcal digis producers
- Drop unsorted ecal/hcal sim hit collections

**Comment by omar-moreno** [comment]
I'm actually thinking we should just sort hits directly in Ecal/Hcal digi processor? Thoughts @awhitbeck ?  However, the limitations you uncovered with the dropping of collections along with the fixes should still be incorporated.

**Comment by omar-moreno** [comment]
@awhitbeck Closing this for now until #424 is resolved.
