### ISSUE TITLE
HCAL veto geometry cut

### ISSUE THREAD

**Issue by bechenard** [LDMX-Software/ldmx-sw#474]

**Comment by omar-moreno** [comment]
@nhanvtran Is this something you want to do since you are making changes to the reconstruction anyway?

**Comment by bechenard** [comment]
Hi guys

If my veto is not in (I would have sworn it was...) then you might want to add it. This is very easily done just cut on the transverse and z direction 

Thanks
Bertrand

**Comment by nhanvtran** [comment]
sure, though I might not get to it today and am away next week.  I can pair it with #479 so it's a self consistent PR with a minPE() cut

**Comment by omar-moreno** [comment]
This was resolved by PR #479 .
