### ISSUE TITLE
Automatic Processor Template Generation

### ISSUE THREAD

**Issue by tomeichlersmith** [LDMX-Software/ldmx-sw#475]
I have written a python script that prints a template header and source file for an input processor name (e.g. HcalDigiProducer) inside an input module (e.g. EventProc). This script includes checks on whether the processor and module already exist, and follows logical decisions for all situations. There also is an option to create a default config and python directory inside the module for the input processor name.

Also, I have edited the central CMakeLists.txt file (ldmx-sw/CMakeLists.txt) to automatically generate the list of modules in an order the considers dependencies between them. This edit would allow for this CMakeLists.txt file to not have to be edited when adding a new module.

**Comment by tomeichlersmith** [comment]
Corresponds to pull request #476

**Comment by tomeichlersmith** [comment]
Now relates to pull request #561 (cleaned up branch commits)

**Comment by omar-moreno** [comment]
This issue was resolved by #561 .
