### ISSUE TITLE
Improve const-correctness of code.

### ISSUE THREAD

**Issue by omar-moreno** [LDMX-Software/ldmx-sw#516]

**Comment by tvami** [comment]
It's a little bit unclear how this was meant to be approached but with https://github.com/LDMX-Software/ldmx-sw/pull/1447 and https://github.com/LDMX-Software/ldmx-sw/pull/1453 and https://github.com/LDMX-Software/ldmx-sw/pull/1460 I think this is resolved. Closing it now (if we should not close it, then we should discuss how to approach it)
