### ISSUE TITLE
Write a new Event Bus Passenger _outside_ of ldmx-sw

### ISSUE THREAD

**Issue by tomeichlersmith** [LDMX-Software/ldmx-sw#644]
Currently, it is required that all event bus passengers are written inside of ldmx-sw or at least added to the `EventBusPassenger` type definition inside of `Event/EventDef.h`.

This may be related to Iss #640 .

Goals:
 - User is able to write and use a new event bus passenger that can be used by processors within `ldmx-app` without making any changes to ldmx-sw

**Comment by tomeichlersmith** [comment]
I've been thinking about this, and I believe we could accomplish this goal with some `cmake` nonsense.

First, a `cmake` macro called e.g. `add_event_object` would be used to declare an event object in any module. This macro would do a few things:
1. Appends the header and source file for the event object to an internal cmake cache list
2. Appends the event object class name to an internal cmake cache list

Then the Event module would have cmake code that writes `EventDef.h` and `EventDefLink.h` depending on the internal lists of event object classes and headers. This would mean the Event module is dependent on all of the other modules at the configure step, but then would be compiled first, combining all of the declared event objects into one library that is accessible by the rest of the modules (especially Framework which needs to know all the event bus passenger types).

**Comment by omar-moreno** [comment]
This makes sense and is straight forward.

**Comment by omar-moreno** [comment]
@tomeichlersmith You going to tackle this? If not, I can get it done today.

**Comment by tomeichlersmith** [comment]
I have a semi-working branch iss644. The tests and recon-only parts are not working. If you want to tackle this, go for it because I'm not sure how much time I can devote to it.

**Comment by omar-moreno** [comment]
Thanks, I'll take over.
