### ISSUE TITLE
Trigger Scintillator Geometry: create new geometry with LYSO active target

### ISSUE THREAD

**Issue by awhitbeck** [LDMX-Software/ldmx-sw#708]
Need to build a geometry where the target and up/down trigger scintillator arrays are removed and replaced by a segmented LYSO target.  Details TBD...

**Comment by awhitbeck** [comment]
#809 marks the first attempt at resolving this.

**Comment by tomeichlersmith** [comment]
I am closing this because we have a lyso-target geometry on `trunk`. If I am mistaken, feel free to re-open and I won't touch it anymore.
