### ISSUE TITLE
Make v9 detector backwards compatible 

### ISSUE THREAD

**Issue by omar-moreno** [LDMX-Software/ldmx-sw#721]

**Comment by tomeichlersmith** [comment]
How is the v9 detector incompatible right now?

**Comment by omar-moreno** [comment]
It's missing regions needed for the biasing to work correctly.  I actually
have an uncommitted fix for this that I have been using for validation ...
let me push this to a branch and get it merged in.

**Comment by omar-moreno** [comment]
We no longer have v9 samples so there is no need to fix this anymore.

**Comment by bryngemark** [comment]
I know that's true at slac, but it's not entirely true: we're basing the 8 GeV paper on v9 (to make as minimal a change possible to the veto paper). This (and that the old samples are gone) is why it might be a really good idea to be able to generate 4 GeV v9 samples, to cross check.

**Comment by omar-moreno** [comment]
Good point! Forgot about the 8 GeV, v9. Thanks for pointing this out.

**Comment by jmmans** [comment]
Is still something which will be fixed, or is now to be closed?
