### ISSUE TITLE
Remove PyROOT requirement

### ISSUE THREAD

**Issue by tomeichlersmith** [LDMX-Software/ldmx-sw#843]
Currently, the only class that _requires_ PyROOT in the C++ is `NonFidEcalVetoProcessor`. If we can either remove or update this class, then we can remove the requirement that PyROOT is installed with ROOT and we can move to a smaller root installation in the container for production.

I've tested building a container with the `-Dminimal=ON` configuration option, and it reduces our container by _a few hundred_ MB. Most users will still want PyROOT installed in the container so they can use other analysis/plotting scripts that they have written, but having a minimal development container would lead to a smaller production container, hopefully speeding up production.

@vdutta Are you familiar with this processor? Do you know if anyone still uses it?

**Comment by vdutta** [comment]
@tomeichlersmith this class can just be removed for now. This class is left over from a time when we played with separate BDTs for fiducial and non-fiducial events, but this was never really used.
