### ISSUE TITLE
ECal Geometry small bugs

### ISSUE THREAD

**Issue by tomeichlersmith** [LDMX-Software/ldmx-sw#861]
- Gap between module hexagons should be 1.5mm instead of only 1mm
   - Just need to update constants.gdml
- center-to-**corner** radius of module hexagons is set to 85mm in `constants.gdml` while the center-to-**flat** radius is set to 85mm in EcalHexReadout.
   - Need to update EcalHexReadout and all the uses of it.

**Comment by omar-moreno** [comment]
OK, we will want to push these changes in before we start production.  As
soon as they are in, I can make a patch release.
