### ISSUE TITLE
Configurations for testing

### ISSUE THREAD

**Issue by tomeichlersmith** [LDMX-Software/ldmx-sw#885]
I think having a `testing` or `test-configs` directory would be helpful. Then we can drop configurations that should be able to be run (without any inputs) into this directory.

I can add another step to the testing GitHub action that would run all the python configs that are in this directory through `fire`. Another option is to to have the test configs go into the `test` directory of the modules. However, this could lead to other issues when mixed with Catch if we aren't careful.

Either way, having a few short python configurations that can test that certain workflows can run would be able to automatically verify that there aren't breaking changes.

**Comment by omar-moreno** [comment]
It's probably best for them to go into the test directory of the modules given that the tests are specific to the modules.
