### ISSUE TITLE
Allow running of Geant4 in interactive mode

### ISSUE THREAD

**Issue by omar-moreno** [LDMX-Software/ldmx-sw#889]
_**Is your feature request related to a problem? Please describe.**
Currently, we aren't able to visualize a detector from the GDML. This requires running in interactive mode. 

**Describe the solution you'd like**
The easiest way to resolve this is to create an executable that allows running in interactive mode. The visualization engine will also be enabled.

**Comment by tomeichlersmith** [comment]
We have a `g4-vis` command merged in to `trunk`, so I'm closing this. If you want to expand the `g4-vis` command to include more potential G4 interactive commands, feel free to re-open this issue.
