### ISSUE TITLE
Small bug in EcalHexReadout

### ISSUE THREAD

**Issue by tomeichlersmith** [LDMX-Software/ldmx-sw#892]
**Describe the bug**
The changes I made to EcalHexReadout left a small part of the module hexagon uncovered by a cell. This will only be noticed if a sim hit happens to hit that small area of the module hexagon, but if that happens, a run-ending exception is thrown.

@omar-moreno Don't start production, this will be a surprise flaw that will end jobs.

**Comment by tomeichlersmith** [comment]
You can see the small area at the corners of module in this map.
[Cell_ID_Cell_Position_Map.pdf](https://github.com/LDMX-Software/ldmx-sw/files/5119900/Cell_ID_Cell_Position_Map.pdf)

**Comment by omar-moreno** [comment]
K, we can hold off for now.
