### ISSUE TITLE
HCAL Scoring Planes empty in latest LDMX-sw

### ISSUE THREAD

**Issue by sophiemiddleton** [LDMX-Software/ldmx-sw#897]
**Describe the bug**
I have noticed in the versions of LDMX-sw > 2.0 that when I run a simulation (even the most simple electron gun) in which I choose to include the scoring planes for all detectors, what I see is hits (sim/rec hits) for the HCAL, ECAL etc. all filled but the HCAL Scoring planes are empty while the scoring planes for the ECAL etc. are not.

**To Reproduce**
1. Go to most recent ldmx-sw
2. run the simulation and attempt to add HCAL scoring planes

**Expected behavior**
I should have seen HCAL Scoring Plane Hits in the same way i see the other hits and also the ECAL Scoring Plane hits.

**Screenshots**

**Desktop (please complete the following information):**
 - currently running on SLAC machines, but I beleive the problem is universal

**Smartphone (please complete the following information):**

**Additional context**
I believe that this is a recent bug (although I have not used versions < 2.0 so cannot confirm from first hand experience.

**Comment by tomeichlersmith** [comment]
I found a bug in the scoring_planes.gdml file where the auxiliary types were being assigned incorrectly, but when I updated them I am now getting a seg fault.... more investigation to follow
