### ISSUE TITLE
CMake/make notices temporary files

### ISSUE THREAD

**Issue by jmmans** [LDMX-Software/ldmx-sw#907]
**Describe the bug**
Emacs creates temporary files (.thefile.cxx) and CMake sees these and decides to add them as new things to compile.  It should probably ignore these...

**To reproduce**
Open a file in emacs and start editing it.  Without saving the file, run make again.  Emacs will write a backup file during editing and make will mess with it.

**Comment by omar-moreno** [comment]
How about turning off temporary files? :)

**Comment by omar-moreno** [comment]
This has been resolved by #644 .
