### ISSUE TITLE
Rename and Clean-Up EcalHexReadout

### ISSUE THREAD

**Issue by tomeichlersmith** [LDMX-Software/ldmx-sw#923]
EcalHexReadout is a class that we are now using for almost all translation between EcalID and real-space position, not just cutting up the module hexagons into cellular hexagons. With this in mind, it makes a lot more sense to call it something more general than `EcalHexReadout`, probably `EcalGeometry` would work best, and then it would line up with the provider that provides it `EcalGeometryProvider`.

I'm also going to take this opportunity to clean-up the Ecal precision digis and the HgcrocEmulator. I need to make the collection name and pass name for the inputs configurable.

@omar-moreno I would love to put all of this Ecal-related stuff in the Ecal module. After the cmake changes you are working on, how difficult would it be to make a "Geometry" sub-module of Ecal (similar to how we are making "Event" submodules)? This way, `SimCore` and `Ecal::Ecal` could link to `Ecal::Geometry` and the source for `Ecal::Geometry` would be in the `Ecal` module.

**Comment by omar-moreno** [comment]
On Thu, Oct 8, 2020 at 1:46 PM Tom Eichlersmith <notifications@github.com>
wrote:

> EcalHexReadout is a class that we are now using for almost all translation
> between EcalID and real-space position, not just cutting up the module
> hexagons into cellular hexagons. With this in mind, it makes a lot more
> sense to call it something more general than EcalHexReadout, probably
> EcalGeometry would work best, and then it would line up with the provider
> that provides it EcalGeometryProvider.
>
> I'm also going to take this opportunity to clean-up the Ecal precision
> digis and the HgcrocEmulator.
>
> @omar-moreno <https://github.com/omar-moreno> I would love to put all of
> this Ecal-related stuff in the Ecal module. After the cmake changes you are
> working on, how difficult would it be to make a "Geometry" sub-module of
> Ecal (similar to how we are making "Event" submodules)? This way, SimCore
> and Ecal::Ecal could link to Ecal::Geometry and the source for
> Ecal::Geometry would be in the Ecal module.
>
This sounds like a good idea. I have already started doing something
similar in SimCore (added SimCore/Geo) and plan to do the same in the
Tracking module.

**Comment by tomeichlersmith** [comment]
> Moving future updates from #873 here.

### Known un-realistic issues to rectify:

- [ ] The cell ID with respect to the x-coordinate will flip between sensitive layers because the modules will be flipped when mounted to make the full layer "sandwich".
- [ ]  Mousebites: The cells do not penetrate into the corners of the module hexagon to leave room for mounting

### Current known layout of module:

![ECal Module Layout](https://user-images.githubusercontent.com/4933600/88490029-16865800-cf5e-11ea-9d07-0a3e26d11121.png)
