### ISSUE TITLE
Add TrigScint clustering and tracking validation plots 

### ISSUE THREAD

**Issue by bryngemark** [LDMX-Software/ldmx-sw#935]
**Is your feature request related to a problem? Please describe.**
We have added two new types of objects to the trigger scintillator collections: clusters and tracks, and they need to be validated when there are new releases (and for data quality later on). 

**Describe the solution you'd like**
We should have a standard set of validation plots for trigger scintillator clusters and tracks just as we do for simhits and reco hits, in the DQM module.

**Comment by tomeichlersmith** [comment]
Now has been included in the auto-validation using the DQM analyzers.
