### ISSUE TITLE
Tracker veto uses hardcoded cut at 1.2 GeV

### ISSUE THREAD

**Issue by bryngemark** [LDMX-Software/ldmx-sw#945]
**Describe the bug**
A hardcoded cut at 1.2 GeV for the tracker veto kills way too many events in 8 GeV simulations!

**Desired behavior**
This should be a configurable parameter. I can't find a standard python config for this processor.

**Comment by omar-moreno** [comment]
This processor has been moved to the Tracker module and updated. It will be available once the v3.0.0 updates are pushed. 

I'm closing this because the issue has been resolved outside of ldmx-sw.
