### ISSUE TITLE
HGC ROC Emulation Improvement

### ISSUE THREAD

**Issue by tomeichlersmith** [LDMX-Software/ldmx-sw#946]
_Context_: While @jmmans and I were debugging the weird behavior of the ECal reconstruction in the v2.3 validation samples, we talked about a lot of long-term improvements that "should" be made to the chip emulator but I didn't want to slow down the already late release.

### Timing Shift
The chip emulator should "know" what its time phase is relative to the simulation global time where t=0ns occurs when the primaries cross z=0mm. In the far future, this would be a conditions table assigning a time phase to each electronic ID corresponding to each chip. Since we aren't really using electronic IDs yet, there needs to be some middleground.

*Potential Solution*: I don't know of a better solution than having the ECal/HCal digi producers do the time shift themselves. They already need to change units from MeV to mV depending on their detector conditions, so this doesn't seem like too big of an ask. In this case, these comments are just warnings for @cmantill .

### Conditions Reliance
The chip emulator currently _can_ take input from a conditions table, but it should _require_ input from a conditions table. This would make HgcrocEmulator more closely resemble HgcrocTriggerCalculations and be more forward thinking.

*Potential Solution* I just need to do this. Not much else to it...

### TOA Measurement
Currently, the simulated time (after accounting for the time phase) is used as the time of the peak of the pulse. This means that for a lot of pulses, the TOA measurement (which is calculated as the time when the pulse goes over the TOA threshold) is negative. This is not realistic (obviously).

*Potential Solution* ~~Use the sim time to set the peak time, then calculate the TOA, then shift the peak so that the calculated TOA corresponds with the actual sim time, then inject noise and actual digitize.~~ The sampling time and the simulated pulse peak time should be close to the center of the clock window. Then we subtract off a shift from the measured TOA in the reconstruction stage so that a nominal high-energy pulse has TOA ~ 0ns (lower energy pulses will "walk" to later TOAs because their pulses are thinner naturally even if they don't actually arrive at a later time).

### Digitization of Multiple Hits
*These comments were generated when looking at how the HCal is going to use the emulator.* PR #958 

Currently, the list of voltage/time pairs at the chip are simply summed/averaged before performing the digitization procedure. This isn't very realistic and requires improvement. Outline of more realistic digitization of multiple hits:

1. Sample each pulse at the sampling times and add them together to construct one pulse.
2. Does the constructed pulse go over the TOT threshold? If so, do TOT mode with our constructed pulse.
3. Pulse did not go over TOT threshold, digitize the samples of the constructed pulse. (a.k.a. ADC mode)

### Other Improvements
Other improvements that can be looked at in this round of developing the emulator are
- Allow for shifting the SOI so that pre-samples can be taken effectively.
- ~~Thoughtfully digitize multiple OOT hits (IT hits are more complicated because of the pre-amp shaping of the pulse).~~
- What do the ADC_t measurements look like during the TOT measurement (i.e. during saturation)? Right now, I'm just measuring a pulse, but I'm fairly certain that is inaccurate. Should it just rail at 1023?

**Comment by jmmans** [comment]
Dear Tom,

Regarding the TOA --> the pulse should be created based on the Sim time, 
but this shouldn't necessarily be set to zero.  Actually, the ideal is 
to _center_ the pulse in the bunch window rather than have it arrive at 
the front edge.  In that case, the TOA should always be in the same 
bunch as the ADC (in the same readout/not negative).

Then, at the /reco/ stage, one needs to subtract the nominal TOA for 
in-time particles.

Jeremy

**Comment by tomeichlersmith** [comment]
TOA measurement should only go into the sample where the pulse _actually_ went over the TOA threshold. The TOA's in the other samples should be a "non-measurement" of 0. The actual TOA measurement should be shifted up by one before being saved so that the "non-measurement" of 0 only happens when the TOA wasn't measured.

**Comment by tomeichlersmith** [comment]
Following lines should be improved. Basically forces TOA to be greater than or equal to zero, which is not realistic.

https://github.com/LDMX-Software/ldmx-sw/blob/5593a7fd9f9e1043bc487cceb54bffc561431bc8/Tools/src/Tools/HgcrocEmulator.cxx#L200-L203

Tied with the time smearing forcing the sim-hit time to be non-negative.

https://github.com/LDMX-Software/ldmx-sw/blob/5593a7fd9f9e1043bc487cceb54bffc561431bc8/Tools/src/Tools/HgcrocEmulator.cxx#L82-L84

**Comment by tomeichlersmith** [comment]
I forgot to link this issue to the recent PR #980  that was merged. I don't think that PR perfectly addressed all of these comments; however, it did address them and I think we need to re-focus any further development on mimic-ing an _actual_ chip.
